version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: ignus
    container_name: ignus-django-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - app-network
    command:
      - /bin/sh
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: